### ISSUE TITLE
Cron job not working (even though script runs)

### ISSUE THREAD

**Issue by daguar** [daguar/netfile-etl#3]
Halp. For some reason the cron job I'm running isn't working.

In crontab, I have:
`20 20 * * * bash /vagrant/Desktop/Innovations/OpenDisclosure/ETL\ Socrata\ Data\ Process/Dave\'s\ CSV\ post-ETL/run_all.sh > /daveslog.txt`

When I run the raw command there, it works fine. But when the cron job runs, it takes a way-too-short amount of time (based on logging) and the CSV outputs are empty.

Is it possible this is running in some async way? (as in, is `python download_and_unzip_files.py` being shot off to run, and then `python etl.py` running but doesn't have the unzipped files yet so just outputs blank stuff -- see below)

In the `run_all.sh` script I have is:

``` bash
echo "Script started at $(date)" >> /vagrant/Desktop/Innovations/OpenDisclosure/ETL\ Socrata\ Data\ Process/Dave\'s\ CSV\ post-ETL/log_for_jobs.txt
cd /vagrant/Desktop/Innovations/OpenDisclosure/ETL\ Socrata\ Data\ Process/Dave\'s\ CSV\ post-ETL/
rm efile*
cd /vagrant/Desktop/Innovations/OpenDisclosure/ETL\ Socrata\ Data\ Process/Dave\'s\ CSV\ post-ETL/
python download_and_unzip_files.py
cd /vagrant/Desktop/Innovations/OpenDisclosure/ETL\ Socrata\ Data\ Process/Dave\'s\ CSV\ post-ETL/
python etl.py
cd /vagrant/Desktop/Innovations/OpenDisclosure/ETL\ Socrata\ Data\ Process/Dave\'s\ CSV\ post-ETL/
python merge_csvs_across_years.py
echo "Script ended at $(date)" >> /vagrant/Desktop/Innovations/OpenDisclosure/ETL\ Socrata\ Data\ Process/Dave\'s\ CSV\ post-ETL/log_for_jobs.txt
```

Notes:
- I threw in all the `cd`s because I thought it might have been running elsewhere
- This is running in sudo crontab

Sorry -- I'm kind of a Unix dummy and haven't done this in forever, so I'm sure there's something simple I'm missing.

Paging @migurski or @spara -- what am I borking here?

**Comment by daguar** [comment]
Also tagging @ted27 @kleinlieu @vbrown608 in case any of you might know what's happening.

**Comment by migurski** [comment]
Can you try running it under "env -i" to see if it works? Sometimes there are environment variables in your shell that are missing under Cron, and -i cleans them out.

**Comment by daguar** [comment]
This was resolved -- in the version using a cron job I specified the full path for `in2csv` in the Python script.
